# This is the developer workflow for the sample project.
#
# Ed Hartnett, 6/2/23

name: developer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  developer:
    runs-on: ubuntu-latest

    steps:
      - name: install-dependencies
        run: |
          sudo apt-get install doxygen
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Build and test.
      - name: build and test
        run: |
          mkdir build
          cd build
          cmake -DENABLE_DOCS=ON ..
          make VERBOSE=1
          make test
